version: '3.5'

services:
  gx-ssi-demonstrator:
    build: .
    image: gx-ssi-demonstrator:latest
    restart: always
    ports:
      - "127.0.0.1:7600:3000"
    environment:
      - SERVER_BASE_URL=${SERVER_BASE_URL:-http://localhost:3000/api}
